version: '3.8'
services:
  db:
    image: mariadb
    container_name: rere_db
    ports:
      - 5432:5432
    environment:
      MARIADB_PASSWORD: MARIADB
      MARIADB_PRIMARY_USER: MARIADB
      MARIADB_PRIMARY_PASSWORD: MARIADB
      MARIADB_USER: MARIADB
      # MARIADB_PASSWORD: MARIADB
      MARIADB_DB: rere
      MODE: MARIADB
      MARIADB_MODE: primary
      MARIADB_ROOT_PASSWORD: MARIADB
      MARIADB_PRIMARY_PORT: 5432
    # networks:
      # vpcbr:
        # ipv4_address: 172.20.1.15
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080