version: '3.8'
services:
  db:
    image: postgres:15-alpine3.16
    container_name: rere_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_PRIMARY_USER: postgres
      POSTGRES_PRIMARY_PASSWORD: postgres
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rere
      MODE: postgres
      POSTGRES_MODE: primary
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_PRIMARY_PORT: 5432
    # networks:
      # vpcbr:
        # ipv4_address: 172.20.1.15
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080